### ISSUE TITLE
Multiple typos

### ISSUE THREAD

**Issue by sierra-sec** [quobyte/quobyte-deploy#19]
Hello, I stumbled upon this error :
``` bash
$ kubectl create -f registry-ds.yaml
Error from server (BadRequest): error when creating "registry-ds.yaml": DaemonSet in version "v1beta1" cannot be handled as a DaemonSet: [pos 178]: json: expect char '"' but got char '1'
```
Just to let you know that changing
``` yaml
spec:
  template:
    metadata:
      labels:
        role: registry
        version: 1.4
```
To
``` yaml
spec:
  template:
    metadata:
      labels:
        role: registry
        version: "1.4"
```
Allowed me to create the DaemonSet.

Cheers !

Edit : Same thing for "webconsole-deployment.yaml","qmgmt-pod.yaml", "data-ds.yaml", "metadata-ds.yaml".

Edit2: Also, spec.template.spec.containers.ports is missing a space.
